spring.application.name=flashy-be

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/flashy
spring.datasource.username=root
spring.datasource.password=anhcuong1
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Mail (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cuonglethe2k4@gmail.com
spring.mail.password=cufz xevx ejrg muzv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# OTP
otp.expiration=300000

# JWT
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# Gemini AI
gemini.api.key=AIzaSyAOKA8KszHEoRGGP4COm4_00N75YXnvbHU